{
 "title": "NTV mixnode",
 "time": { "from": "now-14d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "timeframe",
    "label": "Timeframe (days) for est. rewards",
    "query": "1.0,7.0,30.0,365.0"
   }
  ]
 },
 "panels": [
  {
   "title": "Packets since last polling",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_received_since_last_update\")\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Packets received",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_received_since_startup\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Packets sent",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_sent_since_startup\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total NYM delegated",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")  \r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_delegation\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Accumulated NYM Rewards",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\n  |> filter(fn: (r) => r[\"_field\"] == \"accumulated_rewards\")\n  |> map(fn: (r) => ({r with _value: r._value / 1000000.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Estimated total delegators rewards on $timeframe days",
   "type": "timeseries",
   "description": "to be divided by all delegators proportionally",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\n  |> filter(fn: (r) => r[\"_field\"] == \"estimated_delegators_reward\")\n  |> map(fn: (r) => ({r with _value: (r._value*24.0*${timeframe}) / 1000000.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Estimated total node reward on $timeframe days",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"estimated_total_node_reward\")\r\n  |> map(fn: (r) => ({r with _value: (r._value*24.0*${timeframe}) / 1000000.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Total delegators reward each Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"estimated_delegators_reward\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Total node reward each Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"estimated_total_node_reward\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Total operator reward each Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"estimated_operator_reward\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Estimated operator rewards on $timeframe days",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\n  |> filter(fn: (r) => r[\"_field\"] == \"estimated_operator_reward\")\n  |> map(fn: (r) => ({r with _value: (r._value*24.0*${timeframe}) / 1000000.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Uptime in the mixnet",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"report_last_hour\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: median, createEmpty: false)"
    }
   ]
  },
  { "title": "Advanced stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Gateway - Number of times it has been used for network testing",
   "type": "timeseries",
   "description": "This endpoint returns the number of times that the gateway has been selected from the rewarded set and had 1000 packets sent to it, before being used by the network monitor to test the rest of the network. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"gateway\"] == \"ntv\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Is active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"ntv\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"mixnode\"] == \"ntv\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")"
    }
   ]
  }
 ]
}